import type { ElementType } from "react";
import {
  FaBrain, FaChartLine, FaCloud, FaCode, FaCogs, FaMobileAlt,
  FaRocket, FaUsers,
} from "react-icons/fa";

export type Service = { slug: string; icon: ElementType; label: string; title: string; description: string; points: string[]; footerTitle: string; footerDesc: string; gradient: string; hex: string };

export const services: Service[] = [
  { slug: "ai-intelligent-automation", icon: FaBrain, label: "AI", title: "AI & Intelligent Automation", description: "Harness the power of AI, machine learning, and intelligent automation to streamline operations and deliver smarter customer experiences.", points: ["Machine Learning", "Intelligent Automation", "Smart Experiences"], footerTitle: "Smart Automation", footerDesc: "AI-driven solutions to streamline processes and boost efficiency.", gradient: "from-purple-600 to-violet-600", hex: "#7c3aed" },
  { slug: "data-analytics-business-intelligence", icon: FaChartLine, label: "Data", title: "Data Analytics & Business Intelligence", description: "Turn complex data into meaningful insights with advanced analytics, interactive dashboards, and predictive intelligence.", points: ["Predictive Intelligence", "Interactive Dashboards", "Advanced Analytics"], footerTitle: "Predictive Insights", footerDesc: "Turn raw data into actionable intelligence for better business decisions.", gradient: "from-rose-500 to-pink-600", hex: "#f43f5e" },
  { slug: "cloud-solutions-digital-infrastructure", icon: FaCloud, label: "Cloud", title: "Cloud Solutions & Digital Infrastructure", description: "Build on a secure, scalable, and high-performance cloud infrastructure designed for modern business growth.", points: ["Secure Cloud", "Scalable Infrastructure", "High Performance"], footerTitle: "Cloud Solutions", footerDesc: "Robust and scalable cloud architecture tailored to your business needs.", gradient: "from-sky-500 to-blue-600", hex: "#0ea5e9" },
  { slug: "technology-talent-team-expansion", icon: FaUsers, label: "Talent", title: "Technology Talent & Team Expansion", description: "Strengthen your workforce with experienced developers, designers, engineers, and digital professionals available when you need them.", points: ["Skilled Engineers", "Designers & Architects", "On-Demand Talent"], footerTitle: "Elite Teams", footerDesc: "Access vetted experts who scale your team on demand.", gradient: "from-emerald-500 to-teal-600", hex: "#10b981" },
  { slug: "product-development-mvp-solutions", icon: FaRocket, label: "Product", title: "Product Development & MVP Solutions", description: "Transform innovative ideas into market-ready products through rapid development, agile methodologies, and MVP validation.", points: ["Rapid Development", "Agile Delivery", "MVP Validation"], footerTitle: "Launch Faster", footerDesc: "Ship validated products that reach the market in record time.", gradient: "from-amber-500 to-orange-600", hex: "#f59e0b" },
  { slug: "digital-growth-performance-marketing", icon: FaChartLine, label: "Growth", title: "Digital Growth & Performance Marketing", description: "Accelerate your brand with data-driven strategies, targeted campaigns, and digital marketing solutions focused on measurable growth.", points: ["Data-Driven Strategy", "Targeted Campaigns", "Measurable Growth"], footerTitle: "Measurable Results", footerDesc: "Data-driven campaigns that turn attention into revenue.", gradient: "from-cyan-500 to-teal-500", hex: "#06b6d4" },
  { slug: "digital-products-immersive-experiences", icon: FaMobileAlt, label: "Digital", title: "Digital Products & Immersive Experiences", description: "Create powerful websites, mobile applications, and engaging digital experiences that connect brands with their audiences.", points: ["Websites", "Mobile Applications", "Engaging Experiences"], footerTitle: "Engaging UI", footerDesc: "Craft experiences that delight users and convert visitors.", gradient: "from-blue-500 to-indigo-600", hex: "#2563eb" },
  { slug: "devops-software-delivery", icon: FaCogs, label: "DevOps", title: "DevOps & Software Delivery", description: "Optimize development workflows with automated CI/CD pipelines, cloud-native technologies, and reliable deployment solutions.", points: ["Automated CI/CD", "Cloud-Native", "Reliable Deployments"], footerTitle: "Reliable Delivery", footerDesc: "Automated pipelines that ship software continuously and safely.", gradient: "from-slate-600 to-slate-800", hex: "#475569" },
];
